APPLICATION_NAME = "NCCA Renderfarm 2024"
APPLICATION_VERSION = "1.0.0"
APPLICATION_AUTHORS = ["Christopher Hosken", "ChatGPT"]
APPLICATION_DESCRIPTION = "A cross-platform tool that allows users to interact with the NCCA Renderfarm."

NCCA_ENCRYPTION_KEY_TEXT="NCCA_ENCRYPTION_KEY"
NCCA_USERNAME_KEY_TEXT="NCCA_USERNAME"
NCCA_PASSWORD_KEY_TEXT="NCCA_PASSWORD"

RENDERFARM_ROOT="/home"
RENDERFARM_RENDER_ROOT="/render"


RENDERFARM_SHELL="/bin/bash"
RENDERFARM_PROTOTYPE='cmdrange'