APPLICATION_TITLE = ""
APPLICATION_DESCRIPTION = "A cross-platform tool that allows users to interact with the NCCA Renderfarm."


# Message Info

MESSAGE_INFO_HEADER="NCCA INFO | "

MESSAGE_WARNING_HEADER="NCCA WARNING | "
MESSAGE_WARNING_CONFIRM_TEXT="Ok"

MESSAGE_FATAL_HEADER="NCCA FATAL | "
MESSAGE_FATAL_CONFIRM_TEXT="Quit"


# Custom Labels

MESSAGE_QUBE_LABEL = "Qube"